export const INTERESTS = [
  'Design',
  'Startups',
  'In-person',
  'UX Research',
  'Figma',
  'Design Systems',
  'Motion',
  'AI / Machine Learning',
  'Product Design',
  'Sustainability',
  'Engineering',
  'Data Science',
  'Marketing',
  'Finance',
  'Healthcare',
  'Education',
  'Gaming',
  'Music',
  'Photography',
  'Writing',
  'Architecture',
  'Law',
  'Psychology',
  'Biology',
  'Chemistry',
  'Physics',
  'Mathematics',
  'Economics',
  'Philosophy',
  'Journalism',
] as const;

export type Interest = (typeof INTERESTS)[number];
